//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int uid { get; set; }
        public string uname { get; set; }
        public string upwd { get; set; }
        public string usex { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<int> uiphone { get; set; }
        public string uaddress { get; set; }
    }
}
