//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bpub
    {
        public int bid { get; set; }
        public Nullable<int> uid { get; set; }
        public string btitle { get; set; }
        public string bcon { get; set; }
        public string btype { get; set; }
        public string author { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string bprotrait { get; set; }
        public Nullable<int> count { get; set; }
    }
}
