//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int uid { get; set; }
        public string uname { get; set; }
        public string upass { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string family { get; set; }
        public string marriage { get; set; }
        public string condition { get; set; }
        public string portrait { get; set; }
        public string nickname { get; set; }
    }
}
